app/shelflist/__init__.py
"""
Shelflist package
"""
from app.shelflist.routes import bp  # noqa: F401

app/shelflist/routes.py
"""
Shelflist routes
"""
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request
from flask_login import login_required  # type: ignore
from app.extensions import db
from app.forms.book_form import BookForm
from app.models.book import Book

bp = Blueprint('shelflist', __name__, url_prefix='/shelflist')


@bp.route('/')
@login_required
def index():
    """
    Shelflist index

    :return: shelflist page
    """
    shelflist = Book.get_all_books_with_callnumbers()  # get all books

    return render_template(  # render shelflist page
        'shelflist/index.html',  # template
        shelflist=shelflist,  # shelflist
        title='Library'  # title
    )


@bp.route('/missing-callnumber')
@login_required
def missing_callnumber():
    """
    Shelflist index

    :return: shelflist page
    """
    shelflist = Book.get_books_missing_callnumbers()  # get books missing call numbers

    return render_template(
        'shelflist/missing.html',  # template
        shelflist=shelflist,  # shelflist
        title='Books without Call Numbers'  # title
    )


@bp.route('/<int:isbn>', methods=['GET', 'POST'])
@login_required
def edit_book(isbn):
    """
    Book details

    :param isbn: book isbn
    :return: book details
    """
    book = Book.get_book_by_isbn(isbn)  # try to get book by ISBN

    if book is None:  # if book doesn't exist
        abort(404, f'ISBN {isbn} not found')  # return 404

    form = BookForm(obj=book)  # create form instance with book data

    if form.validate_on_submit():  # if form is submitted
        book.isbn = form.isbn.data  # update isbn
        book.title = form.title.data  # update title
        book.author = form.author.data  # update author
        book.callnumber = form.callnumber.data  # update call number

        db.session.commit()  # commit changes

        flash(  # flash success message
            f'Book "{book.title}" updated',
            'info'
        )

        return redirect(url_for('shelflist.index'))  # redirect to shelflist index

    return render_template(  # render edit page
        'shelflist/edit.html',  # template
        book=book,  # book
        form=form,  # form
        title='Edit "' + book.title + '"'  # title
    )


@bp.route('/<int:isbn>/delete', methods=['GET', 'POST'])
@login_required
def delete_book(isbn):
    """
    Book details

    :param isbn: book isbn
    :return: book details
    """
    book = Book.get_book_by_isbn(isbn)

    if book is None:
        abort(404, f'ISBN {isbn} not found')

    if request.method == 'POST':

        db.session.delete(book)
        db.session.commit()

        flash(
            f'Book "{book.title}" deleted',
            'info'
        )

        return redirect(url_for('shelflist.index'))

    return render_template(
        'shelflist/delete.html',
        book=book,
        title='Delete "' + book.title + '"'
    )

app/templates/shelflist/delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete <em>{{ book.title }}</em></h1>
    <form method="post">
        <div class="mb-3">
            <p>Are you sure you want to delete <em>{{ book.title }}</em>?</p>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{{ url_for('shelflist.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
{% endblock %}

app/templates/shelflist/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit <em>{{ book.title }}</em></h1>
    <form method="post">
        {{ form.csrf_token }}
        <div class="mb-3">
            {{ form.isbn.label(class="form-label") }}
            {{ form.isbn(class="form-control") }}
            {% if form.isbn.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.isbn.errors|join(', ') }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.title.label(class="form-label") }}
            {{ form.title(class="form-control") }}
            {% if form.title.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.title.errors|join(', ') }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.author.label(class="form-label") }}
            {{ form.author(class="form-control") }}
            {% if form.author.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.author.errors|join(', ') }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.callnumber.label(class="form-label") }}
            {{ form.callnumber(class="form-control") }}
            {% if form.callnumber.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.callnumber.errors|join(', ') }}
                </div>
            {% endif %}
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}

app/templates/shelflist/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    {% if shelflist|length == 0 %}
        <div class="alert alert-info" role="alert">
            Your library is empty.
        </div>
    {% endif %}
    <ul class="list-group mb-3">
        {% for book in shelflist %}
            <li class="list-group-item list-group-item-light list-group-item-action">
                <div class="row">
                    <div class="col col-8">
                        {% if book.author is defined %}
                            {{ book.author }},
                        {% endif %}
                        <em><strong>{{ book.title }}</strong></em>
                    </div>
                    <div class="col col-4 text-end">
                        <a href="{{ url_for('shelflist.edit_book', isbn=book.isbn) }}" class="btn btn-primary btn-sm">Edit</a>
                        <a href="{{ url_for('shelflist.delete_book', isbn=book.isbn) }}" class="btn btn-danger btn-sm">Delete</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/shelflist/missing.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col col-8">
            <h1>{{ title }}</h1>
        </div>
        <div class="col col-4 text-end">
            <a href="{{ url_for('shelflist.index') }}" class="btn btn-success">Back to Library</a>
        </div>
    </div>
    {% if shelflist|length == 0 %}
        <div class="alert alert-info" role="alert">
            No books with missing call numbers
        </div>
    {% endif %}
    <ul class="list-group mb-3">
        {% for book in shelflist %}
            <li class="list-group-item list-group-item-light list-group-item-action">
                <div class="row">
                    <div class="col col-8">
                        {% if book.author is defined %}
                            {{ book.author }},
                        {% endif %}
                        <em><strong>{{ book.title }}</strong></em>
                    </div>
                    <div class="col col-4 text-end">
                        <a href="{{ url_for('shelflist.edit_book', isbn=book.isbn) }}" class="btn btn-primary btn-sm">Edit</a>
                        <a href="{{ url_for('shelflist.delete_book', isbn=book.isbn) }}" class="btn btn-danger btn-sm">Delete</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}