app/home/routes.py
"""
Home routes
"""
from flask import Blueprint, redirect, url_for
from flask_login import login_required  # type: ignore

bp = Blueprint('home', __name__)


@bp.route('/')
@login_required
def index():
    """
    Home index

    :return: home page
    """
    return redirect(url_for('shelflist.index'))

app/user/routes.py
"""
User routes
"""
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_required, logout_user  # type: ignore
from werkzeug.security import generate_password_hash
from app.extensions import db
from app.forms.login_form import LoginForm
from app.forms.user_form import UserForm
from app.models.user import User

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/')
def index():
    """
    User index

    :return: redirect to user profile
    """
    return redirect(
        url_for('user.profile')  # redirect to user profile
    )


@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """
    User profile

    :return: user profile
    """
    user = User.get_user(current_user.id)  # get current user
    form = UserForm(obj=user)  # create form instance with user data

    if form.validate_on_submit():  # if form is submitted
        user.email = form.email.data
        user.password = generate_password_hash(form.new_password.data)
        db.session.commit()
        flash('Profile updated', 'success')
        return redirect(url_for('user.profile'))

    return render_template(
        'user/profile.html',
        form=form,
        title='User Profile'
    )


@bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    User login

    :return: login page
    """
    if current_user.is_authenticated:
        return redirect(
            url_for('user.profile')
        )

    form = LoginForm()

    if form.validate_on_submit():

        user = User.user_login(form.email.data, form.password.data)

        if user:

            flash('Login successful', 'success')

            return redirect(
                url_for('home.index')
            )

        flash('Invalid email or password', 'error')

        return redirect(
            url_for('user.login')
        )

    return render_template('user/login.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    """
    User logout

    :return: redirect to login page
    """
    logout_user()

    return redirect(url_for('shelflist.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title is defined %}
            {{ title }} | {{ config.SITE_NAME }}
        {% else %}
            {{ config.SITE_NAME }}
        {% endif %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
{% block header %}
    <header class="header mb-4 text-center">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('home.index') }}">{{ config.SITE_NAME }}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('shelflist.index') }}">Library</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('scanner.index') }}">Scanner</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('user.index') }}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
{% endblock %}

<div class="container mt-3 px-4">
        <div class="messages">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    {% block content %}{% endblock %}
</div>

<div class="container text-center">
    {% block footer %}
        <footer>A Teenie Enterprises Ltd Joint</footer>
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-+0n0l4+XVb3p8v6Zv5Z3ZqJl4VJ6f5ZGJ" crossorigin="anonymous"></script>
</body>
</html>